spring:
  application:
    name: batch

  batch:
    jdbc:
      initialize-schema: always                  # Spring Batch 테이블 자동 생성 (필요 시 never로 설정)
    job:
      enabled: true

  sql:
    init:
      mode: always
      schema-locations: classpath:schema-mysql.sql

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/lab?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: klaatus
    password: 1234

  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate.format_sql: true
      dialect: org.hibernate.dialect.MySQL8InnoDBDialect



  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.xml
    enabled: true

logging:
  level:
    root: INFO
    org.springframework.web: DEBUG